CREATE TABLE noteful_notes (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    note_name TEXT NOT NULL,
    content TEXT NOT NULL,
    modified TIMESTAMPTZ DEFAULT now() NOT NULL,
    folderId INTEGER REFERENCES noteful_folders(id) ON DELETE CASCADE NOT NULL
);
-- postgres turns folderId into folderid (all lowercase)
--make sure client side matches